// ---------------------------------------------------------------------------
// Shared constants for the page builder
// ---------------------------------------------------------------------------

export const TAG_LABELS: Record<string, string> = {
  SECTION: "Section",
  DIV: "Container",
  HEADER: "Header",
  FOOTER: "Footer",
  NAV: "Nav",
  MAIN: "Main",
  ARTICLE: "Article",
  ASIDE: "Aside",
  H1: "Heading 1",
  H2: "Heading 2",
  H3: "Heading 3",
  H4: "Heading 4",
  H5: "Heading 5",
  P: "Paragraph",
  SPAN: "Span",
  IMG: "Image",
  A: "Link",
  BUTTON: "Button",
  UL: "List",
  OL: "List",
  LI: "List Item",
  FORM: "Form",
  INPUT: "Input",
  FIGURE: "Figure",
  FIGCAPTION: "Caption",
  BLOCKQUOTE: "Quote",
  VIDEO: "Video",
  TABLE: "Table",
  TR: "Row",
  TD: "Cell",
  TH: "Header Cell",
  LABEL: "Label",
  SELECT: "Select",
  TEXTAREA: "Text Area",
  PICTURE: "Picture",
  SOURCE: "Source",
};

// Tags to always skip in the layer tree
export const SKIP_TAGS = new Set([
  "SCRIPT",
  "STYLE",
  "LINK",
  "NOSCRIPT",
  "META",
  "HEAD",
  "BR",
  "HR",
  "SVG",
  "PATH",
  "CIRCLE",
  "RECT",
  "LINE",
  "POLYGON",
  "POLYLINE",
  "G",
  "DEFS",
  "CLIPPATH",
  "USE",
  "SYMBOL",
]);
