import { NextResponse } from "next/server";
import { createServerSupabase } from "@/lib/supabase-admin";
import { STORAGE_BUCKET } from "@/lib/constants";
import { STATIC_STYLES } from "@/lib/static-ad-prompt";

// GET /api/genesis/image-bots — the live "Image Prompts" Genesis bots (id, name, description,
// example thumbnail) for the concept-page format picker. Cached in-memory ~10 min.
// Thumbnails are pre-generated by scripts/generate-format-thumbs.ts into
// genesis-format-thumbs/<botId>.png; bots without one simply get no thumbnail.

const THUMB_DIR = "genesis-format-thumbs";

interface Bot {
  id: string;
  name: string;
  description: string;
  recommended?: boolean;
  /** True for the hub's own built-in styles (not Genesis bots). */
  own?: boolean;
  thumbnail?: string;
}

// Pipeline/utility bots that expect a DIFFERENT input (a completed brief, an uploaded ad, or that
// only recommend/expand rather than produce renderable prompts). Given raw ad copy they hallucinate
// (e.g. unaware-static-image-ads-bot produced lifting-strap ads for a puppy course) - hidden from
// the picker.
const EXCLUDED = new Set<string>([
  "unaware-static-image-ads-bot", // transforms completed briefs -> 9:16 prompts
  "static-ad-info-extractor-bot", // pipeline step 1: extracts structured info
  "static-ad-concept-expander-bot", // pipeline step 2: expands structured info
  "static-swipe-bot-", // needs an uploaded competitor ad to reverse-engineer
  "universal-static-bot", // recommends formats, doesn't write prompts
  "universal-static-idea-generator", // idea lists, not renderable prompts
  "1.1-image-gen", // ratio utility
  "reptile-triggers", // superseded by reptile-triggers-bot (takes ad copy directly)
]);

// Proven high-performing formats (from the Copy Coders material) - surfaced first in the picker.
const RECOMMENDED = new Set<string>([
  "ugc-bot-",
  "testimonial-bot-",
  "receipt-bot",
  "reptile-triggers-bot",
  "native-news-bot-",
  "commentreview-transformer-bot-",
  "side-by-sidebefore-and-after-bot-",
  "comparison-bot",
  "statistic-ad-generator-bot",
  "note-from-founder-bot-",
  "hero-bot-",
  "meme-style-ad-concept-generator-bot",
]);

let cache: { at: number; bots: Bot[] } | null = null;

export async function GET() {
  if (cache && Date.now() - cache.at < 10 * 60_000) {
    return NextResponse.json({ bots: cache.bots });
  }
  const key = process.env.GENESIS_API_KEY;
  const base = (process.env.GENESIS_BASE_URL || "https://gas.copycoders.ai/api/v1").replace(/\/+$/, "");
  if (!key) return NextResponse.json({ bots: [], error: "GENESIS_API_KEY not set" }, { status: 200 });

  try {
    const res = await fetch(`${base}/models`, { headers: { Authorization: `Bearer ${key}` } });
    if (!res.ok) return NextResponse.json({ bots: [], error: `models ${res.status}` }, { status: 200 });
    const json = (await res.json()) as { data?: Array<{ id: string; _genesis?: { name?: string; description?: string; category?: string } }> };
    // Which bots have a pre-generated example thumbnail in storage?
    const db = createServerSupabase();
    const { data: thumbFiles } = await db.storage.from(STORAGE_BUCKET).list(THUMB_DIR, { limit: 200 });
    const thumbIds = new Set((thumbFiles ?? []).map((f) => f.name.replace(/\.png$/, "")));
    const thumbUrl = (id: string) => db.storage.from(STORAGE_BUCKET).getPublicUrl(`${THUMB_DIR}/${id}.png`).data.publicUrl;

    const bots: Bot[] = (json.data || [])
      .filter((r) => (r._genesis?.category || "").toLowerCase() === "image prompts" && !EXCLUDED.has(r.id))
      .map((r) => ({
        id: r.id,
        name: r._genesis?.name || r.id,
        description: (r._genesis?.description || "").slice(0, 160),
        recommended: RECOMMENDED.has(r.id),
        ...(thumbIds.has(r.id) ? { thumbnail: thumbUrl(r.id) } : {}),
      }))
      // Recommended first, then alphabetical.
      .sort((a, b) => (a.recommended === b.recommended ? a.name.localeCompare(b.name) : a.recommended ? -1 : 1));

    // The hub's own built-in styles (the old style picker), marked EGEN. Thumbnail = the most
    // recently generated image in that style, so previews come from your real output.
    const styleIds = STATIC_STYLES.map((s) => s.id);
    const { data: recent } = await db
      .from("source_images")
      .select("generation_style, original_url, created_at")
      .in("generation_style", styleIds)
      .order("created_at", { ascending: false })
      .limit(300);
    const latestByStyle = new Map<string, string>();
    for (const r of recent ?? []) {
      if (r.generation_style && !latestByStyle.has(r.generation_style)) latestByStyle.set(r.generation_style, r.original_url);
    }
    const ownFormats: Bot[] = STATIC_STYLES.map((s) => ({
      id: `hub:${s.id}`,
      name: s.label,
      description: s.description,
      own: true,
      ...(latestByStyle.has(s.id) ? { thumbnail: latestByStyle.get(s.id) } : {}),
    }));

    const all = [...bots, ...ownFormats].sort((a, b) =>
      a.recommended === b.recommended ? a.name.localeCompare(b.name) : a.recommended ? -1 : 1,
    );
    cache = { at: Date.now(), bots: all };
    return NextResponse.json({ bots: all });
  } catch (e) {
    return NextResponse.json({ bots: [], error: (e as Error).message }, { status: 200 });
  }
}
